// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 30/01/2026, 23:49:07
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/home/projects/nuxt-starter-2ofdjckc/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/nuxt-starter-2ofdjckc/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/nuxt-starter-2ofdjckc/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/nuxt-starter-2ofdjckc/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/nuxt-starter-2ofdjckc/plugins/**/*.{js,ts,mjs}","/home/projects/nuxt-starter-2ofdjckc/composables/**/*.{js,ts,mjs}","/home/projects/nuxt-starter-2ofdjckc/utils/**/*.{js,ts,mjs}","/home/projects/nuxt-starter-2ofdjckc/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/projects/nuxt-starter-2ofdjckc/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/projects/nuxt-starter-2ofdjckc/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;